export enum Permission {
  // Doctor Permissions
  DOCTOR_VIEW = 'DOCTOR_VIEW',
  DOCTOR_EDIT = 'DOCTOR_EDIT',
  DOCTOR_VERIFY = 'DOCTOR_VERIFY',
  DOCTOR_SUSPEND = 'DOCTOR_SUSPEND',

  // Patient Permissions
  PATIENT_VIEW = 'PATIENT_VIEW',
  PATIENT_EDIT = 'PATIENT_EDIT',
  PATIENT_SUSPEND = 'PATIENT_SUSPEND',

  // Receptionist Permissions
  RECEPTION_CREATE = 'RECEPTION_CREATE',
  RECEPTION_DISABLE = 'RECEPTION_DISABLE',
  RECEPTION_MANAGE = 'RECEPTION_MANAGE',

  // Queue & Token Permissions
  QUEUE_VIEW = 'QUEUE_VIEW',
  QUEUE_MANAGE = 'QUEUE_MANAGE',
  TOKEN_CREATE = 'TOKEN_CREATE',
  TOKEN_CANCEL = 'TOKEN_CANCEL',

  // Consultation & Prescription
  CONSULTATION_CREATE = 'CONSULTATION_CREATE',
  PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE',
  PRESCRIPTION_VIEW = 'PRESCRIPTION_VIEW',

  // Hospital & Clinic
  ORGANIZATION_MANAGE = 'ORGANIZATION_MANAGE',
  ORGANIZATION_VERIFY = 'ORGANIZATION_VERIFY',

  // System & Audit
  ADMIN_ACCESS = 'ADMIN_ACCESS',
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
}
